services:
  ballot-service:
    build:
      context: ./ballot
    container_name: ballot_service
    ports:
      - "6001:5000"
    restart: always
  applicant-db:
    image: mysql:8.0
    container_name: applicant_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: applicant
    ports:
      - "3307:3306"
    volumes:
      - applicant_db_data:/var/lib/mysql
      - ./applicant/applicant.sql:/docker-entrypoint-initdb.d/applicant.sql:ro
    restart: always
  applicant-service:
    build:
      context: ./applicant
    container_name: applicant_service
    ports:
      - "6002:5001"
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:root@applicant-db:3306/applicant
    depends_on:
      - applicant-db
    restart: always
  ballot-audits-db:
    image: mysql:8.0
    container_name: ballot_audits_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ballot_audits
    ports:
      - "3308:3306"
    volumes:
      - ballot_audits_db_data:/var/lib/mysql
      - ./ballot-audits/ballot_audits.sql:/docker-entrypoint-initdb.d/ballot_audits.sql:ro
    restart: always
  ballot-audits-service:
    build:
      context: ./ballot-audits
    container_name: ballot_audits_service
    ports:
      - "6003:5000"
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:root@ballot-audits-db:3306/ballot_audits
    depends_on:
      - ballot-audits-db
    restart: always
  projects-db:
    image: mysql:8.0
    container_name: projects_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projects
    ports:
      - "3309:3306"
    volumes:
      - projects_db_data:/var/lib/mysql
      - ./projects/projects.sql:/docker-entrypoint-initdb.d/projects.sql:ro
    restart: always
  projects-service:
    build:
      context: ./projects
    container_name: projects_service
    ports:
      - "6004:5000"
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:root@projects-db:3306/projects
    depends_on:
      - projects-db
    restart: always

volumes:
  applicant_db_data:
  ballot_audits_db_data:
  projects_db_data:
